apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: thai-practice
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:3ll34ndr0/thai-practice.git
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: thai-practice
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
